### ISSUE TITLE
Where can I find `scn*****_p0_v4.json`?

### ISSUE THREAD

**Issue by sunovivid** [basilevh/gcd#10]
Hi, thank you for the cool work! I think it is novel and brilliant research.

I tried to run evaluation to cite in our paper, but I ran into the following error.

```
(skip previous outputs)

0: Loading input frames from /media/dataset1/kubric4d/test-set/pointcloud/scn02901...
0: Applying Kubric-4D control entry for scn02901...
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 0  wait_time: 0.20
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 1  wait_time: 0.22
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 2  wait_time: 0.24
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 3  wait_time: 0.26
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 4  wait_time: 0.28
Traceback: Traceback (most recent call last):
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/sgm/data/kubric_arbit.py", line 172, in __getitem__
    metadata = common.load_json(metadata_fp)
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/sgm/data/common.py", line 428, in load_json
    with open(fp, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'

Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 5  wait_time: 0.30
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 6  wait_time: 0.32
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 7  wait_time: 0.34
Loading next_example: [2901, 4, 0, False, 15.0, 57.04655, 5.0, 11.268759, 15.0, 12.649029]
Warning: Skipping example that failed to load: scene_idx: 2901  scene_dn: /path/to/Kubric-4D/data/scn02901  exception: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'  retry_idx: 8  wait_time: 0.36
0: Error processing /media/dataset1/kubric4d/test-set/pointcloud/scn02901: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'
Traceback: Traceback (most recent call last):
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/scripts/test.py", line 1018, in worker_fn
    process_example(args, worker_idx, example_idx, example, model_bundle, control_info)
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/scripts/test.py", line 886, in process_example
    (input_rgb, gt_rgb, reproject_rgb, controls, batch) = load_input_gt(
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/scripts/test.py", line 203, in load_input_gt
    batch = my_dset[0]
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/sgm/data/kubric_arbit.py", line 221, in __getitem__
    raise e  # This effectively stops the training job.
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/sgm/data/kubric_arbit.py", line 172, in __getitem__
    metadata = common.load_json(metadata_fp)
  File "/home/cvlab05/project/donghoon/gcd/gcd-model/sgm/data/common.py", line 428, in load_json
    with open(fp, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/Kubric-4D/data/scn02901/scn02901_p0_v4.json'

Skipping...
 100% ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 2/2  [ 0:00:04 < 0:00:00 , 0 it/s ]

0: Done!

Everything took 19.06s

Done!
```

I couldn't find  `scn*****_p0_v4.json` file. I followed the **Dataset Processing** step in `README.md`, but I coudn't see the json file anywhere. How can I get this file? I think I missed something, but I can't find it. It would be very helpful if you could provide some guides.

Thanks again for your awesome work 🥰

**Comment by sunovivid** [comment]
Sorry I noticed that I should chnage the dataset path in training config file too (and move it to {pretrainel_model_path}/config)

I leave this issue for someone like me
